version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: knn_barber_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: ./back
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/knn_barber_app_db
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    command: uvicorn src.entrypoints.fastapi:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
