version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: knn_barber_app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./back/scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
  api:
    build:
      context: ./back
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/knn_barber_app_db
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    command: uvicorn src.entrypoints.fastapi:app --host 0.0.0.0 --port 8000 --reload
  frontend:
    build: 
      context: ./front
    container_name: knn_front
    depends_on:
      - api
    ports:
      - "5173:5173"
    volumes:
    - ./front:/app
    - /app/node_modules
    command: npm run dev --host

volumes:
  postgres_data:
